### ISSUE TITLE
не закрывается уведомление о выполнении задания исполнителем 

### ISSUE THREAD

**Issue by alexander-sanin** [AnthonyBY/Laba42#81]
Шаги воспроизведения:
1. Перейти на сайт laba42.com
2. Залогиниться как заказчик 
3. Создать проект
4. Залогиниться как исполнитель
5. Отклкикнуться на проект из пункта 3
6. Назначить исполнителем пользователя из пункта 4 
7. Отправить отчет о выполнении заказа со стороны исполнителя

Ожидаемый результат:
Появляется сообщение "Один, или несколько ваших исполнителей сообщили о выполнении проектов. Необходимо подтвердить выполнение." которое исчезает при нажатии на крестик

Фактический результат:
Сообщение "Один, или несколько ваших исполнителей сообщили о выполнении проектов. Необходимо подтвердить выполнение." не закрывается при нажатии на крестик и при переходе между вкладками сайта
![vipolnenie](https://user-images.githubusercontent.com/55093235/71368755-d3c06400-25b9-11ea-882d-e5440f53d4dd.png)

**Comment by Almix047** [comment]
> Ожидаемый результат:
> Появляется сообщение "Один, или несколько ваших исполнителей сообщили о выполнении проектов. Необходимо подтвердить выполнение." которое исчезает при нажатии на крестик
> 
> Фактический результат:
> Сообщение "Один, или несколько ваших исполнителей сообщили о выполнении проектов. Необходимо подтвердить выполнение." не закрывается при нажатии на крестик и при переходе между вкладками сайта

Ситуация описанная в `Фактический результат` была реализована в соответствии с  согласованным техническим заданием. Поэтому изменения для реализации описанной в `Ожидаемый результат` нецелесообразны.

Тем не менее, в связи с изменением бизнес-логики затрагивающей подтверждение выполненых проектов даннная опция была убрана. Таким образом появление данного уведомления, которое не закрывается было убрано.
